# Generated by Django 4.2.2 on 2023-07-15 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0002_rename_category1_user_name_remove_user_category2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poi",
            old_name="Address",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="userbucketlist",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="userbucketlist",
            name="poi",
        ),
        migrations.RemoveField(
            model_name="userbucketlist",
            name="start_date",
        ),
        migrations.AddField(
            model_name="poi",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="liked_pois", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userbucketlist",
            name="pois",
            field=models.ManyToManyField(to="nybusy.poi"),
        ),
        migrations.AlterField(
            model_name="userbucketlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
