# Generated by Django 4.2.2 on 2023-07-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0003_rename_address_poi_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="poi",
            name="address",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="category",
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_housenumber",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_postcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="geometry",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="location_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="zone",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="poi",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="tags",
            field=models.ManyToManyField(related_name="pois", to="nybusy.tag"),
        ),
    ]
