# Generated by Django 4.2.2 on 2023-07-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0005_remove_poi_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poi",
            name="addr_city",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="addr_housenumber",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="addr_postcode",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="addr_street",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="description",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="geometry",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="location_id",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="name",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="opening_hours",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="website",
        ),
        migrations.RemoveField(
            model_name="poi",
            name="zone",
        ),
    ]
