# Generated by Django 4.2.2 on 2023-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0006_remove_poi_addr_city_remove_poi_addr_housenumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poi",
            name="addr_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_housenumber",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_postcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="geometry",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="location_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="tags",
            field=models.ManyToManyField(related_name="pois", to="nybusy.tag"),
        ),
        migrations.AddField(
            model_name="poi",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="zone",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
