# Generated by Django 4.2.2 on 2023-07-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0010_alter_poi_options_remove_poi_addr_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poi",
            options={
                "ordering": [
                    "addr_housenumber",
                    "addr_street",
                    "addr_city",
                    "addr_postcode",
                    "description",
                    "name",
                    "opening_hours",
                    "tags",
                    "website",
                    "longitude",
                    "latitude",
                    "location_id",
                    "zone",
                    "geometry",
                ]
            },
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_housenumber",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_postcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="addr_street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="geometry",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="latitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="location_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="longitude",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poi",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poi",
            name="zone",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
