# Generated by Django 4.2.2 on 2023-07-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nybusy",
            "0011_alter_poi_options_poi_addr_city_poi_addr_housenumber_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="poi",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
