# Generated by Django 4.2.2 on 2023-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0012_poi_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poi",
            name="rating",
            field=models.FloatField(blank=True, default=4.5),
            preserve_default=False,
        ),
    ]
