# Generated by Django 4.2.2 on 2023-07-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0014_poiimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(null=True)),
                ("temperature", models.FloatField(null=True)),
                ("humidity", models.FloatField(null=True)),
                ("dewpoint", models.FloatField(null=True)),
                ("apparent_temperature", models.FloatField(null=True)),
                ("precipitation_probability", models.FloatField(null=True)),
                ("rain", models.FloatField(null=True)),
                ("snowfall", models.FloatField(null=True)),
                ("cloudcover", models.FloatField(null=True)),
            ],
        ),
    ]
