# Generated by Django 4.2.2 on 2023-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0015_weatherdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxiZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("some_id", models.IntegerField()),
                ("shape_area", models.FloatField(null=True)),
                ("objectid", models.IntegerField()),
                ("shape_leng", models.FloatField(null=True)),
                ("location_id", models.IntegerField()),
                ("zone", models.CharField(max_length=255)),
                ("borough", models.CharField(max_length=255)),
                ("geometry", models.CharField(max_length=255)),
                ("busy_level", models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
