# Generated by Django 4.2.2 on 2023-07-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0016_taxizone_delete_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.IntegerField()),
                ("busylevel", models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="taxizone",
            name="busy_level",
        ),
        migrations.RemoveField(
            model_name="taxizone",
            name="geometry",
        ),
    ]
