# Generated by Django 4.2.2 on 2023-07-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0021_predictzone_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PredictZone",
        ),
    ]
