# Generated by Django 4.2.2 on 2023-07-25 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0022_delete_predictzone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(null=True)),
                ("busylevel", models.FloatField(null=True)),
                (
                    "location_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nybusy.taxizone",
                    ),
                ),
            ],
        ),
    ]
