# Generated by Django 4.2.3 on 2023-07-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0023_predictzone"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="weathercode",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="windspeed",
            field=models.FloatField(null=True),
        ),
    ]
