# Generated by Django 4.2.3 on 2023-07-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0024_weatherdata_weathercode_weatherdata_windspeed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Predict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(null=True)),
                ("busylevel", models.FloatField(null=True)),
                (
                    "poi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nybusy.poi",
                    ),
                ),
            ],
        ),
    ]
