# Generated by Django 4.2.3 on 2023-07-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0026_rename_predict_predictpoi"),
    ]

    operations = [
        migrations.AddField(
            model_name="poiimage",
            name="imageID",
            field=models.IntegerField(null=True),
        ),
    ]
