# Generated by Django 4.2.3 on 2023-07-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0028_taxizone_multipolygon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxizone",
            old_name="multipolygon",
            new_name="geometry",
        ),
    ]
