# Generated by Django 4.2.3 on 2023-07-31 18:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0029_rename_multipolygon_taxizone_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxizone",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                null=True, srid=4326
            ),
        ),
    ]
