# Generated by Django 4.2.3 on 2023-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0033_userbucketlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictpoi",
            name="time_indext",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="predictzone",
            name="time_indext",
            field=models.IntegerField(null=True),
        ),
    ]
