# Generated by Django 4.2.3 on 2023-08-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0034_predictpoi_time_indext_predictzone_time_indext"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictpoi",
            old_name="time_indext",
            new_name="time_index",
        ),
        migrations.RenameField(
            model_name="predictzone",
            old_name="time_indext",
            new_name="time_index",
        ),
    ]
