# Generated by Django 4.2.3 on 2023-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0036_rename_pois_id_userbucketlist_pois_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictzone",
            name="busyindex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
