# Generated by Django 4.2.3 on 2023-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0037_predictzone_busyindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictpoi",
            name="busyindex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
