# Generated by Django 4.2.3 on 2023-08-10 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nybusy", "0038_predictpoi_busyindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="poi",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="liked_pois", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
